version: '3'

vars:
  PROJECT_NAME: cospec
  VENV_PATH: venv
  PYTHON_BIN: '{{if eq OS "windows"}}venv/Scripts/python{{else}}venv/bin/python{{end}}'
  PIP_BIN: '{{if eq OS "windows"}}venv/Scripts/pip{{else}}venv/bin/pip{{end}}'

tasks:
  setup:
    desc: Setup the project with virtual environment and dependencies
    cmds:
      - 'echo "Setting up {{.PROJECT_NAME}}..."'
      - 'python3 -m venv {{.VENV_PATH}}'
      - '{{.PIP_BIN}} install --upgrade pip'
      - '{{.PIP_BIN}} install -e ".[dev]"'
      - 'echo "Setup complete!"'
      - 'echo "Run: source venv/bin/activate && cospec --help"'

  run:
    desc: Run the cospec CLI tool
    cmds:
      - '{{.PYTHON_BIN}} -m cospec.main'

  hear:
    desc: Run the cospec hear command
    cmds:
      - '{{.PYTHON_BIN}} -m cospec.main hear'

  test-gen:
    desc: Run cospec test-gen command
    cmds:
      - '{{.PYTHON_BIN}} -m cospec.main test-gen'

  agent:
    desc: Run cospec agent commands
    cmds:
      - '{{.PYTHON_BIN}} -m cospec.main agent'

  agent:add:
    desc: Add a new AI-Agent
    cmds:
      - '{{.PYTHON_BIN}} -m cospec.main agent add --help'

  agent:list:
    desc: List all registered AI-Agents
    cmds:
      - '{{.PYTHON_BIN}} -m cospec.main agent list'

  agent:test:
    desc: Test a registered AI-Agent
    cmds:
      - '{{.PYTHON_BIN}} -m cospec.main agent test --help'

  test:
    desc: Run all tests
    cmds:
      - '{{.PYTHON_BIN}} -m pytest'

  test:integration:
    desc: Run integration tests
    cmds:
      - '{{.PYTHON_BIN}} -m pytest tests/integration/ -v'

  test:e2e:
    desc: Run end-to-end tests
    cmds:
      - '{{.PYTHON_BIN}} -m pytest tests/e2e/ -v'

  lint:
    desc: Run linters (ruff check and format)
    cmds:
      - '{{.PYTHON_BIN}} -m ruff check .'
      - '{{.PYTHON_BIN}} -m ruff format --check .'

  lint-fix:
    desc: Run linters and fix issues
    cmds:
      - '{{.PYTHON_BIN}} -m ruff check . --fix'
      - '{{.PYTHON_BIN}} -m ruff format .'

  type-check:
    desc: Run type checking (mypy)
    cmds:
      - '{{.PYTHON_BIN}} -m mypy src/cospec'

  docs:check:
    desc: Check documentation consistency
    cmds:
      - '{{.PYTHON_BIN}} -c "from cospec.core.analyzer import ProjectAnalyzer; a=ProjectAnalyzer(); c=a.collect_context(); print(f\"Collected {len(c)} characters of context\")"'

  docs:sync:
    desc: Synchronize documentation with code
    cmds:
      - 'echo "Documentation synchronization would be implemented here"'

  docs:validate:
    desc: Validate documentation integrity
    cmds:
      - '{{.PYTHON_BIN}} -c "import os; required=[\"docs/SPEC.md\", \"docs/BLUEPRINT.md\", \"docs/PLAN.md\"]; missing=[f for f in required if not os.path.exists(f)]; [print(f\"Missing: {f}\") for f in missing] or print(\"All required docs present\")"'

  quality:check:
    desc: Comprehensive quality check
    cmds:
      - 'task: lint'
      - 'task: type-check'
      - 'task: test'
      - 'task: docs:check'

  build:package:
    desc: Build package distribution
    cmds:
      - '{{.PYTHON_BIN}} -m build'
      - 'ls -la dist/'

  check:
    desc: Run all checks (lint, type-check, test)
    cmds:
      - 'task: lint'
      - 'task: type-check'
      - 'task: test'

  clean:
    desc: Clean up temporary files
    cmds:
      - 'rm -rf {{.VENV_PATH}}'
      - 'rm -rf __pycache__/'
      - 'find . -type f -name "*.pyc" -delete'
      - 'find . -type d -name "__pycache__" -delete'
      - 'rm -rf .ruff_cache/ .mypy_cache/ .pytest_cache/'